### ISSUE TITLE
AttributeError: 'FlashBdev' object has no attribute 'START_SEC'

### ISSUE THREAD

**Issue by dony71** [jedie/micropython-sonoff-webswitch#51]
follow your instruction but firmware stop with error
what could be the problem?

```
load 0x40100000, len 4068, room 16
tail 4
chksum 0xd4
▒8!▒X▒U)▒%▒Pƛt▒▒~ah▒8▒▒A▒▒*P▒▒▒|
                                Q)▒▒nI*▒d9ht▒v▒w▒55B▒-E"▒e|i▒E(▒ ▒▒▒▒8▒n▒▒r▒▒▒n▒b
▒l▒▒l`▒▒▒▒▒▒▒b▒r▒n▒#ܸ▒▒
r▒▒▒▒▒8▒▒▒
▒
r▒▒▒▒I8▒▒▒
▒
r▒▒▒▒I8▒
▒▒▒
▒lrr▒▒l▒Ğ▒▒
▒▒b▒▒b▒$bĒ▒▒b|▒▒ƌ▒
▒l8~▒n▒nܒ▒▒|▒n▒▒▒▒▒l▒
▒l▒
▒▒▒
r▒n▒▒Β▒▒b
▒l▒▒▒▒

















▒b▒▒▒▒ܒ▒▒b
▒
|▒rrr▒nĒ▒▒▒<~▒▒▒▒▒      6▒l▒▒▒bl▒▒▒Performing initial setup
Detected filesystem: 'unknown'
Traceback (most recent call last):
  File "_boot.py", line 11, in <module>
  File "inisetup.py", line 31, in setup
AttributeError: 'FlashBdev' object has no attribute 'START_SEC'
```

**Comment by dony71** [comment]
fix it by changing START_SEC to start_sec in inisetup.py
